# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  profiles: local

server.port: 8080

security:
  ignored: /rest/**,/test/**,/*.js,/sdoc.jsp,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs,/health,/info

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG


endpoints.enabled: false
endpoints.health.enabled: true

sqoop.metastore: jdbc:hsqldb:hsql://localhost:16000/sqoop

oozie.schedule.frequency.minimum: 300

cloudera:
 user: ${cloudera.user:}
 password: ${cloudera.password:}
 url: ${cloudera.address:}
 store: ${cloudera.truststore:}
 storePassword: ${cloudera.truststore.password:}

---

spring:
  profiles: cloud

security:
  ignored: /test/**,/*.js,/sdoc.jsp,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs,/health,/info

spring.oauth2.resource:
  id: tap
  jwt:
    keyUri: ${vcap.services.sso.credentials.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

flyway.initOnMigrate: true

endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.info.sensitive: false

spring.datasource.platform: cloud
spring.jpa.database: POSTGRESQL
spring.datasource: platform=postgres
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: ""
spring.database.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://${postgres.hostname}:${postgres.port}/${postgres.dbname}
spring.datasource.username: ${postgres.username}
spring.datasource.password: ${postgres.password}

oozie.schedule.frequency.minimum: 300
yarn:
  cloudera:
    user: ${cloudera.user:}
    password: ${cloudera.password:}
    store: ${cloudera.truststore:}
    storePassword: ${cloudera.truststore.password:}

# http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git
management:
  info:
    git:
      mode: full

# http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
info:
  name: "@project.artifactId@"
  app_version: "@project.version@"
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    time: "@build.time@"
